version: "3"

services:
  database:
    image: postgres
    env_file:
      - ".env"
    expose:
      - 5432

  web:
    build: .
    env_file:
      - ".env"
    volumes:
      - .:${APP_ROOT}
      - static:$STATIC_ROOT
      - media:$MEDIA_ROOT
    links:
      - database
    ports:
      - 80:8000

volumes:
  static:
    driver: local
  media:
    driver: local