version: '3'

services:
  nginx:
    image: nginx
    env_file:
      - ".env"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot:v1.7.0
    env_file:
      - ".env"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    command: certbot certonly --standalone -d ${SERVER_NAME} --email s1f102101536@iniad.org --agree-tos --no-eff-email