version: '3'

services:
  nginx:
    image: nginx
    env_file:
      - ".env"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
      - /etc/letsencrypt:/etc/letsencrypt
      - static:${STATIC_ROOT}
      - media:${MEDIA_ROOT}
    ports:
      - 80:80
      - 443:443

volumes:
  static:
    driver: local
  media:
    driver: local