version: "3"

services:
  database:
    image: postgres
    env_file:
      - ".env"

  web:
    build: .
    env_file:
      - ".env"
    volumes:
      - .:${APP_ROOT}
      - static:$STATIC_ROOT
      - media:$MEDIA_ROOT
    links:
      - database

volumes:
  static:
    driver: local
  media:
    driver: local