version: '3'

services:
  nginx:
    image: nginx
    env_file:
      - ".env"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
      #- /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      #- "443:443"
    #depends_on:
      #- certbot

  #certbot:
    #image: certbot/certbot
    #env_file:
      #- ".env"
    #volumes:
      #- /etc/letsencrypt:/etc/letsencrypt
    #command: ["certonly", "--standalone", "--email", "example@email.com", "--agree-tos", "--no-eff-email", "-d", "stamp.akabanedai-fes.com"]